name: tests_ubuntu_Octave

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joergbrech/moxunit-action@v1.3.0
        with:
          src: .
          tests: ./tests
          with_coverage: false
