name: moxunit_testCoverage

on: [push, pull_request]

jobs:
  coverage_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joergbrech/moxunit-action@v1.3.0
        with:
          src: .
          tests: ./test/test_mocov_line_covered.m
          with_coverage: true
          cover_xml_file: coverage.xml
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          verbose: true
          fail_ci_if_error: true
          use_oidc: false
        